trigger:
- master

variables:
- template: templates/globalVariables.yml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: templates/posixVariables.yml
  - template: templates/commonPipeline.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  # Note: No job-specific variables for this job
  - template: templates/commonPipeline.yml
